logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8443
  servlet:
    context-path: /clientapp
    session:
      cookie:
        path: /clientapp
  ssl:
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat


spring:
  security:
    oauth2:
      client:
        registration:
          mvisdemoclient:
            client-id: mvisdemoclient
            client-secret: secret
            client-name: MVISDemoClient
            scope: user_info,read
            redirect-uri: https://localhost:8443/clientapp/login/oauth2/code/mvisdemoclient
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            provider: mvisdemoclient-authserver-provider
        provider:
          mvisdemoclient-authserver-provider:
            token-uri: http://localhost:8081/auth/oauth/token
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            user-info-uri: http://localhost:8081/auth/userinfo
            user-name-attribute: username

  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update


